# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_openhomes_pricingmethod_propertytype_region_suburb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0002_auto_20170228_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenced', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fenced')),
                ('title_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title type')),
                ('asking_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Asking price')),
                ('reason_for_selling', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason for selling')),
                ('first_offer_date', models.DateField(blank=True, null=True, verbose_name='First offer date')),
                ('offer_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Offer price')),
                ('walk_away_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Walk away price')),
                ('date_sold', models.DateField(blank=True, null=True, verbose_name='Date sold')),
                ('sale_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Sale price')),
                ('market_reg_value', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Market/reg value')),
                ('owner_rented', models.CharField(blank=True, max_length=255, null=True, verbose_name='Owner/rented')),
                ('rent_per_week', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rent per week')),
                ('rent_appraisal_done', models.BooleanField(default=False, verbose_name='Rent appraisal done')),
                ('insurance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Insurance')),
                ('repairs_maintenance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Repairs & Maintenance')),
                ('body_corporate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Body Corporate')),
                ('other_expenses', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Other expenses')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.House')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
