# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_houseuserdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuserdata',
            name='government_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Government Value'),
        ),
        migrations.AddField(
            model_name='houseuserdata',
            name='rates',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rates'),
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='asking_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Asking price'),
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='market_reg_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Market/reg value'),
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Offer price'),
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Sale price'),
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='walk_away_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='Walk away price'),
        ),
    ]
