# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 13:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_calculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='capital_growth',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Capital Growth rate, %'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='gross_yield',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Gross Yield, %'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='min_cashflow',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min Cashflow, $'),
        ),
        migrations.AlterField(
            model_name='calculator',
            name='net_yield',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Net Yield, %'),
        ),
    ]
