# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20170413_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='weekly_rent',
        ),
    ]
