# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20170417_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseuserdata',
            name='asking_price',
        ),
    ]
