# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_houseuserdata_asking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuserdata',
            name='rent',
            field=models.IntegerField(choices=[(1, 'Current Rent'), (2, 'Agency'), (3, 'PM')], default=1, verbose_name='Rent'),
        ),
    ]
