# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_houseuserdata_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseuserdata',
            name='owner_rented',
        ),
        migrations.RemoveField(
            model_name='houseuserdata',
            name='rent_appraisal_done',
        ),
        migrations.AddField(
            model_name='houseuserdata',
            name='owner_occupied',
            field=models.BooleanField(default=False, verbose_name='Owner occupied'),
        ),
    ]
