# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20170418_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseuserdata',
            name='title_type',
        ),
    ]
