# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_remove_houseuserdata_title_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuserdata',
            name='title_type',
            field=models.IntegerField(choices=[(1, 'Freehold'), (2, 'Crosslease'), (3, 'Leasehold'), (3, 'Unit title')], null=True, verbose_name='Title type'),
        ),
    ]
