# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_houseuserdata_title_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuserdata',
            name='new_build',
            field=models.BooleanField(default=False, verbose_name='New Build'),
        ),
    ]
