# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_houseuserdata_new_build'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseuserdata',
            name='fenced',
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='title_type',
            field=models.IntegerField(choices=[(1, 'Freehold'), (2, 'Crosslease'), (3, 'Leasehold'), (4, 'Unit title')], null=True, verbose_name='Title type'),
        ),
    ]
