# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_auto_20170418_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuserdata',
            name='fenced',
            field=models.IntegerField(blank=True, choices=[(1, 'Fully'), (2, 'Partially'), (3, 'Not fenced')], null=True, verbose_name='Fenced'),
        ),
    ]
