# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_houseuserdata_fenced'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuserdata',
            name='flooding_10',
            field=models.BooleanField(default=False, verbose_name='10 year flooding'),
        ),
        migrations.AddField(
            model_name='houseuserdata',
            name='flooding_100',
            field=models.BooleanField(default=False, verbose_name='100 year flooding'),
        ),
    ]
