# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 12:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_auto_20170419_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseuserdata',
            name='rates',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Council Rates'),
        ),
    ]
