# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 13:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_auto_20170419_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuserdata',
            name='renovations',
            field=models.FloatField(blank=True, null=True, verbose_name='Renovations'),
        ),
        migrations.AddField(
            model_name='houseuserdata',
            name='revisit_on',
            field=models.DateField(blank=True, null=True, verbose_name='Revisit on'),
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='body_corporate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Body Corporate Fees'),
        ),
    ]
