# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 13:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_auto_20170419_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseuserdata',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='houseuserdata',
            name='sold_for',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sold for'),
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='market_reg_value',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Market/reg value'),
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Offer price'),
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='walk_away_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Walk away price'),
        ),
    ]
