# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20170419_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseuserdata',
            name='rent',
        ),
        migrations.AddField(
            model_name='houseuserdata',
            name='rent_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Current Rent'), (2, 'Agency'), (3, 'PM')], null=True, verbose_name='Rent type'),
        ),
    ]
