# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20170419_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseuserdata',
            name='title_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Freehold'), (2, 'Crosslease'), (3, 'Leasehold'), (4, 'Unit title')], null=True, verbose_name='Title type'),
        ),
    ]
