# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170419_1548'),
        ('listings', '0022_auto_20170420_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('value', models.FloatField(verbose_name='Value')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.House')),
            ],
        ),
        migrations.AlterField(
            model_name='houseuserdata',
            name='rent_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Current Rent'), (2, 'Agency'), (3, 'PM')], default=None, null=True, verbose_name='Rent type'),
        ),
    ]
