# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_auto_20170420_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherexpenses',
            name='house',
        ),
        migrations.DeleteModel(
            name='OtherExpenses',
        ),
    ]
