# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_auto_20170420_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
                ('value', models.FloatField(verbose_name='Value')),
                ('house_user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.HouseUserData')),
            ],
        ),
    ]
