# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_auto_20170420_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseuserdata',
            name='other_expenses',
        ),
    ]
