# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 08:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_auto_20170423_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseuserdata',
            name='rent_per_week',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rent per week'),
        ),
    ]
