# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-24 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20170424_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseuserdata',
            name='rent_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Current Rent'), (2, 'Agent provided rent appraisal'), (3, 'Property Manager appraised')], default=None, null=True, verbose_name='Appraisal type'),
        ),
    ]
