# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_manager_user'),
        ('listings', '0032_houseuserdata_appraised_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuserdata',
            name='managers',
            field=models.ManyToManyField(to='managers.Manager', verbose_name='Managers'),
        ),
    ]
