# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 07:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0013_vhousesfortables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('agency', models.CharField(max_length=255, verbose_name='Agency')),
                ('phone_numbers', models.CharField(max_length=255, verbose_name='Phone numbers')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.City')),
            ],
            options={
                'verbose_name_plural': 'Managers',
                'verbose_name': 'Manager',
            },
        ),
    ]
