# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170214_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfiltersettings',
            old_name='search_data_json',
            new_name='filter_data_json',
        ),
    ]
