# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170214_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiltersettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
