# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170219_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFilterSettings',
            new_name='UserFilter',
        ),
    ]
