# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170220_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFilter',
            new_name='HousesFilter',
        ),
    ]
