# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='font_ratio',
            field=models.IntegerField(default=1, verbose_name='Font size'),
        ),
    ]
