# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170307_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='housesfilter',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
