# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_housesfilter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housesfilter',
            name='active',
        ),
        migrations.AddField(
            model_name='housesfilter',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
        ),
        migrations.AlterField(
            model_name='housesfilter',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filter Name'),
        ),
    ]
