# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 13:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20170314_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_interest_rate', models.FloatField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='Loan interest rate, %')),
                ('loan_deposit', models.FloatField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='Loan deposit, %')),
                ('new_built_loan_deposit', models.FloatField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='New-build loan deposit, %')),
                ('property_management_commission', models.FloatField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Property Management commission, %')),
                ('vacancy_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vacancy rate, weeks')),
                ('gross_yield', models.FloatField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Gross yield, %')),
                ('net_yield', models.FloatField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Net yield, %')),
                ('min_cashflow', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min cashflow')),
                ('inflation', models.FloatField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Inflation, %')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
