# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 13:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170410_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='gross_yield',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Gross yield, %'),
        ),
    ]
