# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_calculator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='house',
        ),
        migrations.RemoveField(
            model_name='calculator',
            name='user',
        ),
        migrations.DeleteModel(
            name='Calculator',
        ),
    ]
