# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 10:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20170412_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constants',
            name='gross_yield',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Gross yield, %'),
        ),
        migrations.AlterField(
            model_name='constants',
            name='inflation',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Inflation, %'),
        ),
        migrations.AlterField(
            model_name='constants',
            name='min_cashflow',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min cashflow'),
        ),
        migrations.AlterField(
            model_name='constants',
            name='net_yield',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Net yield, %'),
        ),
        migrations.AlterField(
            model_name='constants',
            name='property_management_commission',
            field=models.FloatField(default=5.0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Property Management commission, %'),
        ),
        migrations.AlterField(
            model_name='constants',
            name='vacancy_rate',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vacancy rate, weeks'),
        ),
    ]
