# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20170523_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telephone'),
        ),
    ]
