# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profile_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_photos_filters',
            field=models.BooleanField(default=True, verbose_name='Show title photo'),
        ),
    ]
