# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 11:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_link', models.CharField(max_length=255, verbose_name='Bond link')),
                ('gst', models.IntegerField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='GST, %')),
                ('qv_link', models.IntegerField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='QV link, %')),
                ('loan_deposit', models.IntegerField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='Loan deposit, %')),
                ('new_built_loan_deposit', models.IntegerField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='New-build loan deposit, %')),
                ('property_management_commission', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Property Management commission, %')),
                ('vacancy_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vacancy rate, weeks')),
                ('gross_yield', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Gross yield, %')),
                ('net_yield', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Net yield, %')),
                ('min_cashflow', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min cashflow')),
                ('inflation', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Inflation, %')),
            ],
        ),
    ]
