# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 12:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='gross_yield',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Gross yield, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='gst',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='GST, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='inflation',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Inflation, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='loan_deposit',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='Loan deposit, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='net_yield',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Net yield, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='new_built_loan_deposit',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='New-build loan deposit, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='property_management_commission',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Property Management commission, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='qv_link',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='QV link, %'),
        ),
    ]
