# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_auto_20170412_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global',
            name='qv_link',
        ),
        migrations.AddField(
            model_name='global',
            name='qv_growth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QV Growth'),
        ),
        migrations.AddField(
            model_name='global',
            name='qv_rental',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QV Rental'),
        ),
        migrations.AddField(
            model_name='global',
            name='qv_sales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QV Sales'),
        ),
    ]
