# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20170417_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='bond_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bond link'),
        ),
    ]
