# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 19:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20170417_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='gross_yield',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Gross yield, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='inflation',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Inflation, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='loan_deposit',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='Loan deposit, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='min_cashflow',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min cashflow'),
        ),
        migrations.AlterField(
            model_name='global',
            name='net_yield',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)], verbose_name='Net yield, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='new_built_loan_deposit',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(95), django.core.validators.MinValueValidator(5)], verbose_name='New-build loan deposit, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='property_management_commission',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Property Management commission, %'),
        ),
        migrations.AlterField(
            model_name='global',
            name='vacancy_rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vacancy rate, weeks'),
        ),
    ]
