# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-28 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_motdbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='qv_growth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QV Growth link'),
        ),
        migrations.AlterField(
            model_name='global',
            name='qv_rental',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QV Rental link'),
        ),
        migrations.AlterField(
            model_name='global',
            name='qv_sales',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QV Sales link'),
        ),
    ]
