# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.TextField(max_length=512, unique=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('work_phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Agencies',
                'verbose_name': 'Agency',
                'db_table': 'agency',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('mobile_phone', models.TextField(blank=True, null=True)),
                ('ddi_phone', models.TextField(blank=True, null=True)),
                ('work_phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Agents',
                'verbose_name': 'Agent',
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255, unique=True)),
                ('capital_growth', models.IntegerField(blank=True, null=True)),
                ('council_link', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Cities',
                'verbose_name': 'City',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('ensuite', models.IntegerField(blank=True, null=True)),
                ('land', models.FloatField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('car_spaces', models.IntegerField(blank=True, null=True)),
                ('property_type', models.IntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_type', models.IntegerField()),
                ('open_homes', models.CharField(blank=True, max_length=1024, null=True)),
                ('auction_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=8192, null=True)),
                ('government_value', models.IntegerField(blank=True, null=True)),
                ('government_rates', models.IntegerField(blank=True, null=True)),
                ('photos', models.CharField(blank=True, max_length=16384, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('additional_data', models.CharField(blank=True, max_length=2048, null=True)),
                ('property_id', models.CharField(blank=True, max_length=16, null=True)),
                ('listing_create_date', models.DateField(blank=True, null=True)),
                ('create_time', models.DateTimeField()),
                ('agency_link', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Houses',
                'verbose_name': 'House',
                'db_table': 'house',
            },
        ),
    ]
