# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'open_homes',
            },
        ),
        migrations.CreateModel(
            name='PricingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Pricing methods',
                'verbose_name': 'Pricing method',
                'db_table': 'pricing_method',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Property types',
                'verbose_name': 'Property type',
                'db_table': 'property_type',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Regions',
                'verbose_name': 'Region',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Suburbs',
                'verbose_name': 'Suburb',
                'db_table': 'suburb',
            },
        ),
    ]
