# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vhousesfortables'),
    ]

    operations = [
        migrations.CreateModel(
            name='VHousesForTables',
            fields=[
                ('house_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('suburb_name', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
                ('region_name', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('price_with_price_type', models.CharField(max_length=255)),
                ('government_value', models.IntegerField()),
                ('government_to_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('land', models.FloatField()),
                ('floor', models.IntegerField()),
                ('property_type_full', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=8192)),
                ('car_spaces', models.IntegerField()),
                ('ensuite', models.BooleanField()),
                ('listing_create_date', models.DateField()),
                ('photos', models.CharField(blank=True, max_length=16384, null=True)),
                ('open_homes_from', models.DateTimeField()),
                ('open_homes_to', models.DateTimeField()),
            ],
            options={
                'db_table': 'v_houses_for_tables',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
