# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170418_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='council_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Council email'),
        ),
        migrations.AddField(
            model_name='city',
            name='council_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Council phone'),
        ),
        migrations.AddField(
            model_name='city',
            name='flooding_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Flooding link'),
        ),
        migrations.AddField(
            model_name='city',
            name='property_bag_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Property bag link'),
        ),
        migrations.AddField(
            model_name='city',
            name='rates_link_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rates link #1'),
        ),
        migrations.AddField(
            model_name='city',
            name='rates_link_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rates link #2'),
        ),
        migrations.AlterField(
            model_name='city',
            name='capital_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='City name'),
        ),
    ]
