# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170418_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lim_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lim link'),
        ),
    ]
