# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-19 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170419_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': False, 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
