# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170419_1548'),
    ]

    operations = [
        migrations.RunSQL("""
            ALTER TABLE `city` CHANGE COLUMN `council_email` `council_email` VARCHAR(255);
            ALTER TABLE `city` CHANGE COLUMN `council_phone` `council_phone` VARCHAR(255);
            ALTER TABLE `city` CHANGE COLUMN `flooding_link` `flooding_link` VARCHAR(255);
            ALTER TABLE `city` CHANGE COLUMN `property_bag_link` `property_bag_link` VARCHAR(255);
            ALTER TABLE `city` CHANGE COLUMN `rates_link_1` `rates_link_1` VARCHAR(255);
            ALTER TABLE `city` CHANGE COLUMN `rates_link_2` `rates_link_2` VARCHAR(255);
            ALTER TABLE `city` CHANGE COLUMN `lim_link` `lim_link` VARCHAR(255);
        """)
    ]
