# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_vhousesfortables'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonds', models.IntegerField()),
                ('median_rent', models.IntegerField()),
                ('median_e', models.IntegerField()),
                ('gross_yield', models.FloatField()),
                ('annual_rent_change', models.FloatField()),
                ('annual_e_change', models.FloatField()),
                ('bedrooms', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'rental_analysis',
            },
        ),
        migrations.CreateModel(
            name='SalesPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sales', models.IntegerField()),
                ('median_sale_price', models.IntegerField()),
                ('difference', models.FloatField()),
                ('capital_value_date', models.DateField()),
            ],
            options={
                'managed': False,
                'db_table': 'sales_prices',
            },
        ),
    ]
